### ISSUE TITLE
Make country and language a parameter?

### ISSUE THREAD

**Issue by ticky** [sampsyo/wideq#13]
It seems like it’d be helpful to allow the user to change the country code - I just tested with editing the “US” and “en-US” to be “CA” and “en-CA” respectively and everything works - but for upstream implementations like `hass-smartthinq` that’s trickier to do!

**Comment by sampsyo** [comment]
Yes, absolutely! I've been meaning to do this. Here's what needs to change in this module:

- Parameterize the `gateway_info` function.
- Add parameters to the `Gateway` class's `discover` class method.
- Add parameters to `Client` and feed them into the `Gateway` construction.
- Add CLI options to `example.py` to control the country and language. (This might require using a proper option parsing library instead of just using `sys.argv` directly.)

Then we can add a configuration option to the Home Assistant component that uses these parameters. Any help here would be greatly appreciated.

**Comment by sampsyo** [comment]
I've added a parameter.
