### ISSUE TITLE
Refrigerator support

### ISSUE THREAD

**Issue by impankratov** [sampsyo/wideq#44]
Hi,

I'm willing to add refrigerator support but I don't know how I can pull the actual property/command names from refrigerator. 

Can you provide any advice on how you've done it with currently supported devices?

**Comment by sampsyo** [comment]
Hi! I did it with a combination of dumping the model spec information and browsing the source code of the mobile app. If you try querying for the device data for your refrigerator, you can print the model information JSON and see if it’s useful.

**Comment by impankratov** [comment]
@sampsyo I've actually pulled device-specific JSON schema of some sorts and a zip archive with the app. What stopped me is the fact that all JavaScript there was minified/uglified.

Ok then, I guess I'll need to dig a little bit more. Thanks for help!

**Comment by sampsyo** [comment]
Yeah, it's pretty difficult with the minified JS. FWIW, I have used [JSNice](http://www.jsnice.org/) to make things a little more readable.

Also, while the details escape me, I recall that the API actually provides little "app modules" for each device for the mobile app, consisting of HTML and JavaScript for the UI for that particular device. You can see the link to this archive in the device information. I seem to recall that this per-module JS was not minified, or at least it was *less* obfuscated. (Although it was somewhat hard to tell because the spaghetti code was so gnarled...)

**Comment by guy16510** [comment]
If I wanted to control my fridge, would any of you folks have a good place to start? It sounds like the only way is viewing the source code of the app? Would any of you specifically have the APIs involved, and I figure I could go from there. Thanks for your help.

**Comment by NorDroN** [comment]
See PR #65
